# Rutas relativas desde donde ejecutes el script o rutas absolutas
path: ../data/raw/bdd100k  # Root dir 

train: images/100k/train  # Carpeta de imágenes de entrenamiento
val: images/100k/val      # Carpeta de imágenes de validación
# test:  (opcional)

# Nota: YOLO buscará automáticamente una carpeta "labels" paralela a "images"
# Estructura esperada:
# data/raw/bdd100k/
#    ├── images/100k/val/imagen1.jpg
#    └── labels/100k/val/imagen1.txt  <-- (Debes mover los txt generados aquí o ajustar la estructura)

# Classes
nc: 10  # number of classes
names: ['pedestrian', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle', 'bicycle', 'traffic light', 'traffic sign']